Update check-thrift-change.yml

diff --git a/.github/workflows/check-thrift-change.yml b/.github/workflows/check-thrift-change.yml
--- a/.github/workflows/check-thrift-change.yml
+++ b/.github/workflows/check-thrift-change.yml
@@ -32,25 +32,33 @@ jobs:
        with:
           fetch-depth: 0  
      - name: Find Thrift files
-       run: |
-          files=$(git diff --name-only HEAD^ HEAD | grep "\.thrift$")
-          echo "::set-output name=files::$files"
-
+          changed_thrift_files=$(git diff --name-only HEAD^ HEAD | grep "\.thrift$")
+          echo "::set-output name=changed_thrift_files::$changed_thrift_files"
      - name: Check Thrift files
-       run: |
-          for file in ${{ steps.find.outputs.files }}; do
-            if grep -q "^enum.*{$" $file && grep -q "^enum.*{-" $file; then
-              echo "Error: $file contains deleted enum fields"
-              exit 1
-            fi
+       run: |  
+            for file in ${{ steps.find.outputs.changed_thrift_files }}; do
+              # 判断是新增还是修改
+              if git log --pretty=format:%s -1 $file | grep -q "create mode"; then
+                echo "$file is a new Thrift file"
+              else
+                echo "$file is a modified Thrift file"
+              fi
 
-            if ! grep -q "^enum" $file; then
-              echo "Error: $file contains non-enum structures"
-              exit 1
-            fi
+              # 判断是否修改了结构体
+              if grep -q "^struct" $file; then
+                # 判断是否新增了字段
+                if git diff HEAD^ HEAD -- $file | grep -q "^\+.*:.*;"; then
+                  # 判断新增的字段是否为可选字段
+                  if ! git diff HEAD^ HEAD -- $file | grep -q "^\+.*:.*\?;"; then
+                   echo "Error: $file contains added required fields in struct"
+                    exit 1
+                  fi
+                fi
 
-            if grep -q "required" $file; then
-              echo "Error: $file contains required fields"
-              exit 1
-            fi
-          done
+                # 判断是否删除了字段
+                if git diff HEAD^ HEAD -- $file | grep -q "^\-.*:.*;"; then
+                  echo "Error: $file contains deleted fields in struct"
+                  exit 1
+                fi
+              fi
+            done
