create Kafka docker env

diff --git a/.github/workflows/check-thrift.yml b/.github/workflows/check-thrift.yml
--- a/.github/workflows/check-thrift.yml
+++ b/.github/workflows/check-thrift.yml
@@ -31,29 +31,35 @@ jobs:
           fetch-depth: 0
       - name: Check Thrift files
         run: |
-          for file in ${{ steps.find.outputs.changed_thrift_files }}; do
-                            # 判断是新增还是修改
-                            if git log --pretty=format:%s -1 $file | grep -q "create mode"; then
-                              echo "$file is a new Thrift file"
-                            else
-                              echo "$file is a modified Thrift file"
-                            fi
-      
-                            # 判断是否修改了结构体
-                            if grep -q "^struct" $file; then
-                              # 判断是否新增了字段
-                              if git diff HEAD^ HEAD -- $file | grep -q "^\+.*:.*;"; then
-                                # 判断新增的字段是否为可选字段
-                                if ! git diff HEAD^ HEAD -- $file | grep -q "^\+.*:.*\?;"; then
-                                 echo "Error: $file contains added required fields in struct"
-                                  exit 1
-                                fi
-                              fi
-      
-                              # 判断是否删除了字段
-                              if git diff HEAD^ HEAD -- $file | grep -q "^\-.*:.*;"; then
-                                echo "Error: $file contains deleted fields in struct"
-                                exit 1
-                              fi
-                            fi
+          changed_files=$(git diff --name-only HEAD^ HEAD | grep "\.thrift$")
+          # 如果没有Thrift文件更改，则退出脚本
+          if [[ -z "$changed_files" ]]
+          then
+          echo "No Thrift files have been changed"
+          exit 0
+          fi
+  
+          # 循环检查每个更改的Thrift文件
+          for file in $changed_files
+          do
+          # 提取文件名和文件路径
+          file_name=$(basename $file)
+          file_path=$(dirname $file)
+          
+          # 判断Thrift是新增字段还是新增结构
+          if grep -qP "struct $file_name\b" $file
+          then
+          echo "Thrift新增结构 $file_name"
+          else
+          echo "Thrift新增字段"
+          # 提取新增字段名
+          new_field=$(diff <(grep -oP 'struct \K\w+' $file_path/$file_name) <(grep -oP 'struct \K\w+' $file) | grep '>' | grep -oP '\.\K\w+')
+          # 检查新增字段是否为required
+          is_required=$(grep -oP "required \K$new_field" $file)
+          if [[ "$is_required" == "required" ]]
+          then
+          echo "新增字段 $new_field 为required，出现错误"
+          exit 1
+          fi
+          fi
           done
